"""update rule model for conditions and actions

Revision ID: 5639fc5b84fd
Revises: efaa2a98a686
Create Date: 2025-05-15 02:54:44.982730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5639fc5b84fd'
down_revision: Union[str, None] = 'efaa2a98a686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_conditions',
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('condition_type_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition_type_id'], ['condition_types.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], )
    )
    op.add_column('rules', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('action_description', sa.Text(), nullable=True))
    op.drop_column('rules', 'condition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('rules', 'action_description')
    op.drop_column('rules', 'description')
    op.drop_table('rule_conditions')
    # ### end Alembic commands ###
