"""condition schema

Revision ID: dec1af5b369b
Revises: 216fcb3f40db
Create Date: 2025-05-15 05:09:48.616624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec1af5b369b'
down_revision: Union[str, None] = '216fcb3f40db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_types_field'), 'condition_types', ['field'], unique=True)
    op.create_index(op.f('ix_condition_types_id'), 'condition_types', ['id'], unique=False)
    op.create_index(op.f('ix_condition_types_name'), 'condition_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_condition_types_name'), table_name='condition_types')
    op.drop_index(op.f('ix_condition_types_id'), table_name='condition_types')
    op.drop_index(op.f('ix_condition_types_field'), table_name='condition_types')
    op.drop_table('condition_types')
    # ### end Alembic commands ###
