"""add options and year_field to condition_types

Revision ID: efaa2a98a686
Revises: dec1af5b369b
Create Date: 2025-05-15 02:47:42.431966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaa2a98a686'
down_revision: Union[str, None] = 'dec1af5b369b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condition_types', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('condition_types', sa.Column('year_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('condition_types', 'year_field')
    op.drop_column('condition_types', 'options')
    # ### end Alembic commands ###
